# Generated by Django 2.0.5 on 2021-02-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='update_date',
        ),
    ]
