# Generated by Django 2.0.5 on 2021-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210207_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='summer', max_length=200, unique=True)),
                ('index', models.IntegerField(default=1, null=True)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seasons',
            field=models.ManyToManyField(to='shop.Season'),
        ),
    ]
