# Generated by Django 2.0.5 on 2021-02-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210220_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('index',), 'verbose_name': 'season', 'verbose_name_plural': 'seasons'},
        ),
    ]
