# Generated by Django 2.0.5 on 2021-02-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210220_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='season_slug',
        ),
    ]
