# Generated by Django 2.0.5 on 2021-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_season_season_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(db_index=True, default='Summer', max_length=200),
        ),
    ]
