# Generated by Django 2.0.5 on 2021-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_season_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(default='spring', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(db_index=True, default='Spring', max_length=200),
        ),
    ]
