# Generated by Django 2.0.5 on 2021-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210220_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Women', max_length=200)),
                ('slug', models.SlugField(default='women', max_length=200, unique=True)),
                ('index', models.IntegerField(default=1, null=True)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
