# Generated by Django 2.0.5 on 2021-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(to='shop.Genre'),
        ),
    ]
