# Generated by Django 2.0.5 on 2021-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_color',
            field=models.CharField(choices=[('uncertain', '未定'), ('red', '紅'), ('orange', '橙'), ('yellow', '黃'), ('pink', '粉紅'), ('cyan', '青'), ('blue', '藍'), ('purple', '紫'), ('green', '綠'), ('gray', '灰'), ('black', '黑'), ('white', '白'), ('brown', '咖啡')], default='uncertain', max_length=50),
        ),
    ]
