# Generated by Django 2.0.5 on 2021-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210221_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('index',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
