# Generated by Django 2.0.5 on 2021-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210224_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='styles',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Uniqlo', 'Uniqlo'), ('GU', 'GU'), ('NET', 'NET'), ('Lativ', 'Lativ'), ('H&M', 'H&M')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_color',
            field=models.CharField(blank=True, choices=[('red', '紅'), ('orange', '橙'), ('yellow', '黃'), ('pink', '粉紅'), ('cyan', '青'), ('blue', '藍'), ('purple', '紫'), ('green', '綠'), ('gray', '灰'), ('black', '黑'), ('white', '白'), ('brown', '咖啡')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, choices=[('thick', '厚'), ('average', '中'), ('thin', '薄')], db_index=True, max_length=200, null=True),
        ),
    ]
